"""Unit tests for the mesh fitting functionality."""

import logging
from pathlib import Path

import numpy as np
import pytest
import trimesh.transformations as tf
import yaml

from fleetmaster import FleetMaster
from fleetmaster.core.engine import run_simulation_batch
from fleetmaster.core.settings import SimulationSettings

# Configure basic logging
logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)


@pytest.fixture(scope="module")
def regression_hdf5_path() -> Path:
    """
    Generates the HDF5 database from a settings file in `tests/data`.
    This ensures tests run against a consistent database generated by the
    current code based on the committed YAML configuration.
    """
    # 1. Setup paths
    settings_path = Path("tests/data/settings.yml").resolve()
    output_hdf5_path = Path("tests/data/boxship.hdf5").resolve()

    if not settings_path.exists():
        pytest.fail(f"Settings file not found at {settings_path}. This test requires it to exist.")

    # 2. Load settings from the YAML file
    with open(settings_path) as f:
        config = yaml.safe_load(f)
    settings = SimulationSettings(**config)

    # 3. Make file paths absolute relative to the settings file
    settings_dir = settings_path.parent
    if settings.base_mesh:
        settings.base_mesh = str(settings_dir / settings.base_mesh)

    for mesh_config in settings.stl_files:
        mesh_config.file = str(settings_dir / mesh_config.file)

    # 4. Override settings for the test environment
    settings.output_directory = str(output_hdf5_path.parent)
    settings.output_hdf5_file = str(output_hdf5_path.name)
    settings.overwrite_meshes = True  # Ensure we always regenerate for the test

    # 5. Run the database generation
    run_simulation_batch(settings)

    return output_hdf5_path


# --- Original Test Cases ---

# (The TEST_CASES list remains unchanged)
TEST_CASES = [
    (
        "Case 1: Exact Match Draft 1 meter",
        [0.0, 0.0, -1.0],
        [0.0, 0.0, 0.0],
        0.0,
        "boxship_t_1_r_00_00_00",
        0.0,
    ),
    (
        "Case 2: Match with irrelevant translation/rotation noise (draft 1.0)",
        [2.5, -4.2, -1.1],
        [0.0, 0.0, 15.0],
        0.0,
        "boxship_t_1_r_00_00_00",
        0.0,
    ),
    (
        "Case 3: Different match due to significant rotation deviation (draft 1.0)",
        [2.5, -4.2, -1.1],
        [23.0, 19.0, 15.0],
        0.0,
        "boxship_t_1_r_20_20_00",
        0.0,
    ),
    (
        "Case 4: Exact Match for draft 2.0",
        [0.0, 0.0, -2.0],
        [0.0, 0.0, 0.0],
        0.0,
        "boxship_t_2_r_00_00_00",
        0.0,
    ),
    (
        "Case 5: Exact Match for draft 2.0 with irrelevant xy-plane and yaw deviation",
        [10.0, -20.0, -2.0],
        [0.0, 0.0, 15.0],
        0.0,
        "boxship_t_2_r_00_00_00",
        0.0,
    ),
    (
        "Case 6: Match for draft 2.0 with noise in all axes",
        [10.0, -20.0, -2.2],
        [4.0, -1.0, 15.0],
        0.0,
        "boxship_t_2_r_00_00_00",
        0.16944,
    ),
]


@pytest.mark.parametrize(
    "description, target_translation, target_rotation, water_level, expected_match, expected_distance",
    TEST_CASES,
    ids=[case[0] for case in TEST_CASES],
)
def test_fleetmaster_fitting(
    regression_hdf5_path: Path,
    description: str,
    target_translation: list[float],
    target_rotation: list[float],
    water_level: float,
    expected_match: str,
    expected_distance: float,
):
    """Tests the FleetMaster mesh fitting with various scenarios."""
    logger.info(f"Running test: {description}")

    fm = FleetMaster(filename=regression_hdf5_path)

    fm.set_waterdepth(water_level)
    fm.set_velocity(0.0)

    angles_rad = np.deg2rad(target_rotation)
    rot = tf.euler_matrix(angles_rad[0], angles_rad[1], angles_rad[2], axes="sxyz")
    transform = rot.copy()
    transform[0:3, 3] = target_translation

    fm.fit_mesh(transform=transform)

    best_match = fm.get_best_match_name()
    distance = fm.get_match_error()

    assert best_match is not None, "A best match should have been found."
    assert best_match == expected_match
    np.testing.assert_almost_equal(
        distance,
        expected_distance,
        decimal=5,
        err_msg=f"Distance check failed for {description}. Got distance: {distance}, expected: {expected_distance}.",
    )
