"""Unit tests for the mesh fitting functionality."""

import logging
from pathlib import Path

import numpy as np
import pytest
import trimesh.transformations as tf

from fleetmaster import FleetMaster
from fleetmaster.core.engine import run_simulation_batch
from fleetmaster.core.settings import MeshConfig, SimulationSettings

# Configure basic logging
logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)


@pytest.fixture(scope="function")
def regression_hdf5_path(tmp_path_factory, file_regression) -> Path:
    """
    Generates the HDF5 database from a single base STL and a set of transformations,
    validates it against a regression fixture, and provides its path.
    This ensures tests run against a consistent database generated by the current code.
    """
    # 1. Setup paths
    tmp_dir = tmp_path_factory.mktemp("db_generation")
    # As established, we refer to the source STL file in-place.
    base_stl_path = Path("examples/boxship.stl").resolve()
    output_hdf5_path = tmp_dir / "boxship_regression.hdf5"

    if not base_stl_path.exists():
        pytest.fail(f"Base STL file not found at {base_stl_path}. This test requires it to exist.")

    # 2. Define the transformations to be applied to the base mesh.
    # This mirrors the setup from settings_rotations.yml, but instead of pointing
    # to pre-generated files, we point to the same base file and let the engine
    # apply the transformations.
    mesh_configs = [
        MeshConfig(
            file=str(base_stl_path),
            name="boxship_t_1_r_00_00_00",
            translation=[0.0, 0.0, -1.0],
            rotation=[0.0, 0.0, 0.0],
            cog=[0.0, 0.0, 0.0],
        ),
        MeshConfig(
            file=str(base_stl_path),
            name="boxship_t_2_r_00_00_00",
            translation=[0.0, 0.0, -2.0],
            rotation=[0.0, 0.0, 0.0],
            cog=[0.0, 0.0, 0.0],
        ),
        MeshConfig(
            file=str(base_stl_path),
            name="boxship_t_1_r_45_00_00",
            translation=[0.0, 0.0, -1.0],
            rotation=[45.0, 0.0, 0.0],
            cog=[0.0, 0.0, 0.0],
        ),
        MeshConfig(
            file=str(base_stl_path),
            name="boxship_t_1_r_00_10_00",
            translation=[0.0, 0.0, -1.0],
            rotation=[0.0, 10.0, 0.0],
            cog=[0.0, 0.0, 0.0],
        ),
        MeshConfig(
            file=str(base_stl_path),
            name="boxship_t_1_r_20_20_00",
            translation=[0.0, 0.0, -1.0],
            rotation=[20.0, 20.0, 0.0],
            cog=[0.0, 0.0, 0.0],
        ),
    ]

    # 3. Define SimulationSettings programmatically
    settings = SimulationSettings(
        base_mesh=str(base_stl_path),
        base_origin=[0, 0.0, 1.5],
        output_hdf5_file=str(output_hdf5_path),
        grid_symmetry=False,
        stl_files=mesh_configs,
        wave_periods=list(np.arange(0.5, 20.1, 0.5)),
        wave_directions=list(np.arange(0, 181, 22.5)),
        overwrite_meshes=True,  # Ensure we always regenerate for the test
    )

    # 4. Run the database generation
    run_simulation_batch(settings)

    # 5. Check the generated HDF5 file against the golden master
    with open(output_hdf5_path, "rb") as f:
        file_regression.check(f.read())

    return output_hdf5_path


# --- Original Test Cases ---

# (The TEST_CASES list remains unchanged)
TEST_CASES = [
    (
        "Case 1: Exact Match Draft 1 meter",
        [0.0, 0.0, -1.0],
        [0.0, 0.0, 0.0],
        0.0,
        "boxship_t_1_r_00_00_00",
        0.0,
    ),
    (
        "Case 2: Match with irrelevant translation/rotation noise (draft 1.0)",
        [2.5, -4.2, -1.1],
        [0.0, 0.0, 15.0],
        0.0,
        "boxship_t_1_r_00_00_00",
        0.0,
    ),
    (
        "Case 3: Different match due to significant rotation deviation (draft 1.0)",
        [2.5, -4.2, -1.1],
        [23.0, 19.0, 15.0],
        0.0,
        "boxship_t_1_r_20_20_00",
        0.0,
    ),
    (
        "Case 4: Exact Match for draft 2.0",
        [0.0, 0.0, -2.0],
        [0.0, 0.0, 0.0],
        0.0,
        "boxship_t_2_r_00_00_00",
        0.0,
    ),
    (
        "Case 5: Exact Match for draft 2.0 with irrelevant xy-plane and yaw deviation",
        [10.0, -20.0, -2.0],
        [0.0, 0.0, 15.0],
        0.0,
        "boxship_t_2_r_00_00_00",
        0.0,
    ),
    (
        "Case 6: Match for draft 2.0 with noise in all axes",
        [10.0, -20.0, -2.2],
        [4.0, -1.0, 15.0],
        0.0,
        "boxship_t_2_r_00_00_00",
        0.16944,
    ),
]


@pytest.mark.parametrize(
    "description, target_translation, target_rotation, water_level, expected_match, expected_distance",
    TEST_CASES,
    ids=[case[0] for case in TEST_CASES],
)
def test_fleetmaster_fitting(
    regression_hdf5_path: Path,
    description: str,
    target_translation: list[float],
    target_rotation: list[float],
    water_level: float,
    expected_match: str,
    expected_distance: float,
):
    """Tests the FleetMaster mesh fitting with various scenarios."""
    logger.info(f"Running test: {description}")

    fm = FleetMaster(filename=regression_hdf5_path)

    fm.set_waterdepth(water_level)
    fm.set_velocity(0.0)

    angles_rad = np.deg2rad(target_rotation)
    rot = tf.euler_matrix(angles_rad[0], angles_rad[1], angles_rad[2], axes="sxyz")
    transform = rot.copy()
    transform[0:3, 3] = target_translation

    fm.fit_mesh(transform=transform)

    best_match = fm.get_best_match_name()
    distance = fm.get_match_error()

    assert best_match is not None, "A best match should have been found."
    assert best_match == expected_match
    np.testing.assert_almost_equal(
        distance,
        expected_distance,
        decimal=5,
        err_msg=f"Distance check failed for {description}. Got distance: {distance}, expected: {expected_distance}.",
    )
