"""
Example script to demonstrate the mesh fitting functionality using the FleetMaster class.

This script uses the `FleetMaster` class to find the best
fit for a given transformation from a pre-existing HDF5 database.
"""

import logging
from pathlib import Path

import numpy as np
import trimesh.transformations as tf

from fleetmaster import FleetMaster

# Configure basic logging to see the output from the fitting function
logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)


def _run_and_print_test_case(
    case_number: int,
    description: str,
    fm: FleetMaster,
    translation: list[float],
    rotation_deg: list[float],
    note: str = "",
):
    """Runs a single fitting test case and prints the results."""
    print(f"\n\n--- Running Test Case {case_number}: {description} ---")
    logger.info(f"Searching for best match for translation={translation}, rotation={rotation_deg}...")

    # Construct transformation matrix
    angles_rad = np.deg2rad(rotation_deg)
    # build rotation matrix using Euler angles with 'sxyz' convention
    rot = tf.euler_matrix(angles_rad[0], angles_rad[1], angles_rad[2], axes="sxyz")
    # form full 4x4 transformation by inserting translation
    transform = rot.copy()
    transform[0:3, 3] = translation

    # Run the fit
    fm.fit(transform=transform)

    # Get the results
    error = fm.get_match_error()
    hyddb, _origin, _velocity, _waterdepth = fm.get_hyddb1()

    print(f"\n--- Result for Test Case {case_number} ---")
    if error != np.inf:
        print(f"✅ Best match found with error: {error:.6f}")
        if hyddb:
            print(f"   - Successfully retrieved Hyddb1 object with {hyddb.n_frequencies} frequencies.")
            # Demonstrate saving the hyddb1 object
            try:
                hyd_filename = f"case_{case_number}.hyd"
                hyddb.to_hyd_file(hyd_filename)
                print(f"   - Saved Hyddb1 object to '{hyd_filename}'")
            except Exception as e:
                print(f"   - Failed to save Hyddb1 object: {e}")

        if note:
            print(f"   - Note: {note}")
    else:
        print("❌ No match found.")


def run_fleetmaster_fitting_example():
    """
    Runs the fitting example using the FleetMaster class.
    """
    # Path to the HDF5 database file generated by the settings_rotations.yml example.
    hdf5_path = Path(__file__).parent / "boxship.hdf5"
    if not hdf5_path.exists():
        logger.error(f"Database file not found at: {hdf5_path}")
        logger.error("Please run 'fleetmaster -v run --settings-file examples/settings_rotations.yml' first.")
        return

    # Instantiate FleetMaster
    fm = FleetMaster(filename=hdf5_path)

    # Set parameters (these are used in the fitting process)
    fm.set_waterdepth(0.0)  # Corresponds to water_level in the original example
    fm.set_velocity(0.0)  # Assuming 0 velocity for these cases

    # --- Test Case 1: A transformation that should perfectly match an existing mesh ---
    _run_and_print_test_case(
        case_number=1,
        description="Exact Match Draft 1 meter",
        fm=fm,
        translation=[0.0, 0.0, -1.0],
        rotation_deg=[20.0, 20.0, 0.0],
    )

    # --- Test Case 2: A transformation with irrelevant translations and rotations ---
    _run_and_print_test_case(
        case_number=2,
        description="Match with Noise draft 1.0",
        fm=fm,
        translation=[2.5, -4.2, -1.1],  # Added dx, dy and dz
        rotation_deg=[20.0, 20.0, 15.0],  # Added yaw
        note="The distance should be very close to the distance in Case 1.",
    )


if __name__ == "__main__":
    run_fleetmaster_fitting_example()
